apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patchesStrategicMerge:
  - storageclass.yaml
  - controller.yaml
  - mutatingwebhooks.yaml
  - node.yaml
  - scheduler.yaml
resources:
  - ../../deploy/manifests/overlays/daemonset-scheduler
  - provisioner.yaml
generatorOptions:
  disableNameSuffixHash: true
configurations:
  - kustomizeconfig.yaml
secretGenerator:
- name: mutatingwebhook
  namespace: topolvm-system
  files:
  - ca.crt=../certs/cert.pem
  - tls.crt=../certs/cert.pem
  - tls.key=../certs/key.pem
  type: "Opaque"
vars:
  - name: TLSCERT
    objref:
      kind: Secret
      version: v1
      name: mutatingwebhook
    fieldref:
      fieldpath: data[ca.crt]
