apiVersion: v2
type: application

home: https://github.com/topolvm/topolvm
name: topolvm
description: Topolvm
version: 4.0.0
appVersion: 0.10.4
sources:
  - https://github.com/topolvm/topolvm

dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: 1.3.1
    condition: cert-manager.enabled
