apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
spec:
  template:
    spec:
      containers:
        - name: topolvm-scheduler
          image: topolvm:dev
---
apiVersion: v1
kind: Service
metadata:
  namespace: topolvm-system
  name: topolvm-scheduler
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 9251
    nodePort: 30251
