name: "e2e-k8s"
on:
  pull_request:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
  push:
    paths-ignore:
      - "**/*.md"
      - "CODEOWNERS"
    branches:
      - "main"

jobs:
  default:
    uses: ./.github/workflows/e2e-k8s-workflow.yaml

  scheduler-manifest:
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      test_scheduler_manifest: "deployment"

  storage-capacity:
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      storage_capacity: "true"

  skip-node-finalize:
    uses: ./.github/workflows/e2e-k8s-workflow.yaml
    with:
      skip_node_finalize: "true"
