name: "Release Charts"

on: "workflow_dispatch"

jobs:
  release:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Configure Git"
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: "Get Helm version"
        id: helm_version
        run: |
          HELM_VERSION=$(awk -F= '/^HELM_VERSION/ { print $2 }' Makefile)
          echo "::set-output name=value::${HELM_VERSION}"

      - name: "Install Helm"
        uses: azure/setup-helm@v3
        with:
          version: "v${{ steps.helm_version.value }}"

      # Add depending repository for helm to avoid the error below.
      # `Error: no repository definition for https://charts.jetstack.io`
      # see: https://github.com/helm/chart-releaser-action/issues/74
      - name: "Add cert-manager repo for helm"
        run: |
          helm repo add cert-manager https://charts.jetstack.io

      - name: "Run chart-releaser"
        uses: helm/chart-releaser-action@v1.4.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
