name: Main
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
        id: go
      - run: make setup
      - run: |
          mkdir -p $HOME/go
          cd $HOME/go
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          go get golang.org/x/tools/cmd/goimports
          go get golang.org/x/lint/golint
          go get github.com/gordonklaus/ineffassign
          go get github.com/tcnksm/ghr
          go get github.com/gostaticanalysis/nilerr/cmd/nilerr
          go get github.com/cybozu/neco-containers/golang/analyzer/cmd/...
      - run: |
          make manifests generate
          diffs=$(git diff --name-only)
          if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
      - run: |
          export PATH=$PATH:$HOME/go/bin
          make test
      - run: |
          export GOPATH=$HOME/go
          make build
