name: Main
on: [push]
jobs:
  build:
    name: build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make setup
      - run: env GOPATH=${HOME}/go make setup
      - run: |
          make manifests generate
          diffs=$(git diff --name-only)
          if [ "$diffs" != "" ]; then printf "%s\n" "$diffs"; exit 1; fi
      - run: make test
      - run: make build
      - run: make image
  test-node:
    name: test-node
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: install lvm2
        run: |
          sudo apt-get update
          sudo apt-get -y install --no-install-recommends lvm2
      - run: sudo -E env PATH=${PATH} GO111MODULE=on go test -mod=vendor -race -v ./lvmd ./driver ./filesystem
  e2e-k8s:
    name: e2e-k8s
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        test_kubernetes_version: [1.17, 1.16, 1.15]
    env:
      TEST_KUBERNETES_VERSION: ${{ matrix.test_kubernetes_version }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - run: make setup
      - run: make -C e2e setup
      - run: make -C e2e start-lvmd
      - run: make -C e2e test
